import { Lead, Salesman, ReferralItem, CallLog, LeadCategoryItem, NotificationItem, ReportRow } from './types';

export const mockSalesmen: Salesman[] = [
  {
    id: 's1',
    name: 'Md. Rahim Sarder',
    title: 'Sr. Real Estate Executive',
    department: 'Luxury Residential & Commercial',
    avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&q=80&w=200',
    phone: '01640510100',
    email: 'rahim.sarder@promiseassets.com',
    totalLeadAssign: 60,
    bookedSold: 30,
    contacted: 30,
    lost: 30,
    performanceRate: 50,
    score: '92/100',
    isTopPerformer: true,
  },
  {
    id: 's2',
    name: 'Siddique Rahman',
    title: 'Senior Property Advisor',
    department: 'Bashundhara & Purbachal Plots',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=200',
    phone: '01712345678',
    email: 'siddique.r@promiseassets.com',
    totalLeadAssign: 75,
    bookedSold: 42,
    contacted: 25,
    lost: 8,
    performanceRate: 90,
    score: '95/100',
    isTopPerformer: true,
  },
  {
    id: 's3',
    name: 'Md. Karim Shah',
    title: 'Senior Real Estate Consultant',
    department: 'Gulshan & Banani Luxury Enclave',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=200',
    phone: '01640510101',
    email: 'karim56@gmail.com',
    totalLeadAssign: 50,
    bookedSold: 20,
    contacted: 20,
    lost: 10,
    performanceRate: 78,
    score: '88/100',
  },
  {
    id: 's4',
    name: 'Nazma Begum',
    title: 'Commercial Property Lead',
    department: 'Uttara Commercial Towers',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=200',
    phone: '01898765432',
    email: 'nazma.begum@promiseassets.com',
    totalLeadAssign: 60,
    bookedSold: 30,
    contacted: 30,
    lost: 30,
    performanceRate: 50,
    score: '82/100',
  }
];

export const initialLeads: Lead[] = [
  {
    id: 'L01',
    sl: '01',
    date: '01.01.2026',
    name: 'Md. Rahim Mia',
    phone: '01700066699',
    email: 'jccdhaka@gmail.com',
    occupation: 'Businessman',
    nid: '256983698',
    address: 'Kallayanpur, Dhaka',
    projectName: 'Purbachal Green Valley Project',
    requiredPlotSize: '5 Katha',
    facingPreference: 'South',
    budgetLimit: '৳ 1.5 Crore',
    projectType: 'Plot',
    prefTime: 'Morning',
    status: 'Enrolled',
    assignedSalesman: 'Siddique Rahman',
    source: 'Facebook',
    lastCallDate: '2026-02-20',
    callCount: 3,
    messageCount: 3,
    note: 'Interest to book 5 Katha South Facing plot by 14-03-2026',
  },
  {
    id: 'L02',
    sl: '02',
    date: '02.01.2026',
    name: 'Raja Jisan Khan',
    phone: '01700066699',
    email: 'jccdhaka@gmail.com',
    occupation: 'Corporate GM',
    nid: '198273645',
    address: 'Kallayanpur, Dhaka',
    projectName: 'Bashundhara Block-I Luxury Heights',
    requiredPlotSize: '2400 sqft',
    facingPreference: 'North',
    budgetLimit: '৳ 2.2 Crore',
    projectType: 'Residential',
    prefTime: 'Night',
    status: 'Lost',
    assignedSalesman: 'Siddique Rahman',
    source: 'Facebook',
    lastCallDate: '2026-02-20',
    callCount: 3,
    messageCount: 3,
    note: 'Budget Problem',
    lostReason: 'Budget'
  },
  {
    id: 'L03',
    sl: '03',
    date: '03.01.2026',
    name: 'Karim Khandokar',
    phone: '01700066699',
    email: 'jccdhaka@gmail.com',
    occupation: 'Doctor',
    nid: '887766554',
    address: 'Kallayanpur, Dhaka',
    projectName: 'Gulshan Avenue Commercial Plaza',
    requiredPlotSize: '1800 sqft',
    facingPreference: 'Corner',
    budgetLimit: '৳ 3.5 Crore',
    projectType: 'Commercial',
    prefTime: 'Evening',
    status: 'Contacted',
    assignedSalesman: 'Md. Rahim Sarder',
    source: 'WhatsApp',
    lastCallDate: '2026-02-20',
    callCount: 4,
    messageCount: 2,
    note: 'Scheduled site visit for upcoming Saturday'
  },
  {
    id: 'L04',
    sl: '04',
    date: '04.01.2026',
    name: 'Abdul Karim',
    phone: '01700066699',
    email: 'jccdhaka@gmail.com',
    occupation: 'Expatriate (Dubai)',
    nid: '445566778',
    address: 'Banani, Dhaka',
    projectName: 'Purbachal Sector 4 Villa Project',
    requiredPlotSize: '10 Katha',
    facingPreference: 'South',
    budgetLimit: '৳ 4.0 Crore',
    projectType: 'Luxury Villa',
    prefTime: 'Afternoon',
    status: 'Follow Up',
    assignedSalesman: 'Siddique Rahman',
    source: 'Youtube',
    lastCallDate: '2026-02-20',
    callCount: 3,
    messageCount: 3,
    note: 'Waiting for bank loan approval from HSBC'
  },
  {
    id: 'L05',
    sl: '05',
    date: '05.01.2026',
    name: 'Rajib Hossain',
    phone: '01700066699',
    email: 'jccdhaka@gmail.com',
    occupation: 'Software Architect',
    nid: '998877665',
    address: 'Dhanmondi, Dhaka',
    projectName: 'Dhanmondi Lake View Luxury Condo',
    requiredPlotSize: '2100 sqft',
    facingPreference: 'East',
    budgetLimit: '৳ 1.8 Crore',
    projectType: 'Residential',
    prefTime: 'Morning',
    status: 'Interested',
    assignedSalesman: 'Md. Karim Shah',
    source: 'Facebook',
    lastCallDate: '2026-02-20',
    callCount: 2,
    messageCount: 5,
    note: 'Requested updated floor plan and payment schedule'
  },
  {
    id: 'L06',
    sl: '06',
    date: '06.01.2026',
    name: 'Tabassum Tuha',
    phone: '01700066699',
    email: 'jccdhaka@gmail.com',
    occupation: 'Professor',
    nid: '332211445',
    address: 'Uttara, Dhaka',
    projectName: 'Uttara Model Town Sector 11 Plot',
    requiredPlotSize: '3 Katha',
    facingPreference: 'South',
    budgetLimit: '৳ 1.2 Crore',
    projectType: 'Plot',
    prefTime: 'Afternoon',
    status: 'Site Visit',
    assignedSalesman: 'Siddique Rahman',
    source: 'Portal',
    lastCallDate: '2026-02-20',
    callCount: 5,
    messageCount: 4,
    note: 'Site visit completed. Interested in booking token.'
  },
  {
    id: 'L07',
    sl: '07',
    date: '07.01.2026',
    name: 'Dr. Sharmin Sultana',
    phone: '01811223344',
    email: 'sharmin.s@gmail.com',
    occupation: 'Surgeon',
    nid: '554433221',
    address: 'Banani Block-E, Dhaka',
    projectName: 'Banani Block-E Luxury Apartment',
    requiredPlotSize: '2800 sqft',
    facingPreference: 'South',
    budgetLimit: '৳ 3.8 Crore',
    projectType: 'Residential',
    prefTime: 'Evening',
    status: 'Enrolled',
    assignedSalesman: 'Md. Rahim Sarder',
    source: 'Portal',
    lastCallDate: '2026-02-21',
    callCount: 4,
    messageCount: 6,
    note: 'Booking deposit cleared for 4th floor south unit'
  },
  {
    id: 'L08',
    sl: '08',
    date: '08.01.2026',
    name: 'Engr. Anisur Rahman',
    phone: '01922334455',
    email: 'anis.engr@yahoo.com',
    occupation: 'Civil Engineer',
    nid: '667788990',
    address: 'Mirpur DOHS, Dhaka',
    projectName: 'Jolshiri Abashon Block-B Plot',
    requiredPlotSize: '5 Katha',
    facingPreference: 'South',
    budgetLimit: '৳ 1.6 Crore',
    projectType: 'Plot',
    prefTime: 'Morning',
    status: 'Follow Up',
    assignedSalesman: 'Nazma Begum',
    source: 'Facebook',
    lastCallDate: '2026-02-22',
    callCount: 2,
    messageCount: 1,
    note: 'Asking for soil test & Rajuk approval documents'
  },
  {
    id: 'L09',
    sl: '09',
    date: '09.01.2026',
    name: 'Kazi Rafiqul Islam',
    phone: '01633445566',
    email: 'kazi.rafiq@gmail.com',
    occupation: 'Importer & Exporter',
    nid: '112233445',
    address: 'Agrabad, Chattogram',
    projectName: 'Chattogram Agrabad Commercial Suite',
    requiredPlotSize: '1500 sqft',
    facingPreference: 'Corner',
    budgetLimit: '৳ 2.5 Crore',
    projectType: 'Commercial',
    prefTime: 'Afternoon',
    status: 'Contacted',
    assignedSalesman: 'Siddique Rahman',
    source: 'Portal',
    lastCallDate: '2026-02-22',
    callCount: 3,
    messageCount: 2,
    note: 'Wants to setup corporate office suite on 6th floor'
  },
  {
    id: 'L10',
    sl: '10',
    date: '10.01.2026',
    name: 'Md. Tanvir Ahmed',
    phone: '01744556677',
    email: 'tanvir.a@gmail.com',
    occupation: 'Bank Manager',
    nid: '778899001',
    address: 'Savar, Dhaka',
    projectName: 'Savar Prime Housing Plot',
    requiredPlotSize: '4 Katha',
    facingPreference: 'East',
    budgetLimit: '৳ 80 Lakh',
    projectType: 'Plot',
    prefTime: 'Evening',
    status: 'Interested',
    assignedSalesman: 'Md. Karim Shah',
    source: 'Facebook',
    lastCallDate: '2026-02-23',
    callCount: 1,
    messageCount: 3,
    note: 'Inquiring about 36-month equal installment plan'
  },
  {
    id: 'L11',
    sl: '11',
    date: '11.01.2026',
    name: 'Nasreen Sultana',
    phone: '01855667788',
    email: 'nasreen.s@outlook.com',
    occupation: 'Businesswoman',
    nid: '223344556',
    address: 'Gazipur Sadar',
    projectName: 'Gazipur Smart City Villa',
    requiredPlotSize: '6 Katha',
    facingPreference: 'North',
    budgetLimit: '৳ 1.1 Crore',
    projectType: 'Luxury Villa',
    prefTime: 'Morning',
    status: 'Enrolled',
    assignedSalesman: 'Nazma Begum',
    source: 'Portal',
    lastCallDate: '2026-02-23',
    callCount: 5,
    messageCount: 8,
    note: 'Token allotment completed. Registration scheduled.'
  },
  {
    id: 'L12',
    sl: '12',
    date: '12.01.2026',
    name: 'Capt. Mahmud Hasan',
    phone: '01966778899',
    email: 'mahmud.captain@gmail.com',
    occupation: 'Airline Pilot',
    nid: '889900112',
    address: 'Uttara Sector 3, Dhaka',
    projectName: 'Cox\'s Bazar Sea Facing Condo',
    requiredPlotSize: '1600 sqft',
    facingPreference: 'West',
    budgetLimit: '৳ 1.9 Crore',
    projectType: 'Luxury Villa',
    prefTime: 'Night',
    status: 'Site Visit',
    assignedSalesman: 'Md. Rahim Sarder',
    source: 'Youtube',
    lastCallDate: '2026-02-24',
    callCount: 3,
    messageCount: 4,
    note: 'Flight schedule back in Dhaka on Friday for site inspection'
  },
  {
    id: 'L13',
    sl: '13',
    date: '13.01.2026',
    name: 'Syeda Nusrat Jahan',
    phone: '01677889900',
    email: 'nusrat.syeda@gmail.com',
    occupation: 'Govt. First Class Officer',
    nid: '334455667',
    address: 'Mirpur DOHS, Dhaka',
    projectName: 'Mirpur DOHS Duplex Villa',
    requiredPlotSize: '3200 sqft',
    facingPreference: 'South',
    budgetLimit: '৳ 4.2 Crore',
    projectType: 'Luxury Villa',
    prefTime: 'Morning',
    status: 'Follow Up',
    assignedSalesman: 'Siddique Rahman',
    source: 'Portal',
    lastCallDate: '2026-02-24',
    callCount: 2,
    messageCount: 2,
    note: 'Awaiting house loan sanction letter from Sonali Bank'
  },
  {
    id: 'L14',
    sl: '14',
    date: '14.01.2026',
    name: 'Tariqul Islam Chowdhury',
    phone: '01788990011',
    email: 'tariq.sylhet@gmail.com',
    occupation: 'Expatriate (UK)',
    nid: '990011223',
    address: 'Zindabazar, Sylhet',
    projectName: 'Sylhet Rose View Residency',
    requiredPlotSize: '2200 sqft',
    facingPreference: 'East',
    budgetLimit: '৳ 1.4 Crore',
    projectType: 'Residential',
    prefTime: 'Evening',
    status: 'Contacted',
    assignedSalesman: 'Md. Karim Shah',
    source: 'WhatsApp',
    lastCallDate: '2026-02-25',
    callCount: 4,
    messageCount: 5,
    note: 'Inquired about power of attorney & NRI allotment terms'
  },
  {
    id: 'L15',
    sl: '15',
    date: '15.01.2026',
    name: 'Prof. Humayun Kabir',
    phone: '01899001122',
    email: 'humayun.kabir@du.ac.bd',
    occupation: 'University Dean',
    nid: '445566778',
    address: 'Baridhara Diplomatic Zone, Dhaka',
    projectName: 'Baridhara Diplomatic Zone Flat',
    requiredPlotSize: '3500 sqft',
    facingPreference: 'North',
    budgetLimit: '৳ 6.5 Crore',
    projectType: 'Residential',
    prefTime: 'Afternoon',
    status: 'Enrolled',
    assignedSalesman: 'Md. Rahim Sarder',
    source: 'Portal',
    lastCallDate: '2026-02-25',
    callCount: 6,
    messageCount: 10,
    note: 'Final contract signed. Down payment received.'
  },
  {
    id: 'L16',
    sl: '16',
    date: '16.01.2026',
    name: 'Mahmuda Akter',
    phone: '01900112233',
    email: 'mahmuda.a@gmail.com',
    occupation: 'School Principal',
    nid: '556677889',
    address: 'Narayanganj Sadar',
    projectName: 'Narayanganj Riverfront Plot',
    requiredPlotSize: '5 Katha',
    facingPreference: 'South',
    budgetLimit: '৳ 95 Lakh',
    projectType: 'Plot',
    prefTime: 'Morning',
    status: 'Interested',
    assignedSalesman: 'Nazma Begum',
    source: 'Facebook',
    lastCallDate: '2026-02-26',
    callCount: 2,
    messageCount: 3,
    note: 'Evaluating riverfront plot demarcation map'
  },
  {
    id: 'L17',
    sl: '17',
    date: '17.01.2026',
    name: 'Asif Mahmud',
    phone: '01611223344',
    email: 'asif.m@techbd.com',
    occupation: 'Tech Entrepreneur',
    nid: '112233445',
    address: 'Uttara Sector 14, Dhaka',
    projectName: 'Uttara Sector 14 Commercial Plot',
    requiredPlotSize: '3 Katha',
    facingPreference: 'Corner',
    budgetLimit: '৳ 2.8 Crore',
    projectType: 'Commercial',
    prefTime: 'Afternoon',
    status: 'Follow Up',
    assignedSalesman: 'Siddique Rahman',
    source: 'Portal',
    lastCallDate: '2026-02-26',
    callCount: 3,
    messageCount: 4,
    note: 'Inquired about height allowance & FAR calculation'
  },
  {
    id: 'L18',
    sl: '18',
    date: '18.01.2026',
    name: 'Dr. Farhana Chowdhury',
    phone: '01722334455',
    email: 'farhana.dr@gmail.com',
    occupation: 'Medical Officer',
    nid: '667788990',
    address: 'Khulna Sadar',
    projectName: 'Khulna City View Apartment',
    requiredPlotSize: '1900 sqft',
    facingPreference: 'South',
    budgetLimit: '৳ 1.1 Crore',
    projectType: 'Residential',
    prefTime: 'Night',
    status: 'Site Visit',
    assignedSalesman: 'Md. Karim Shah',
    source: 'Facebook',
    lastCallDate: '2026-02-27',
    callCount: 2,
    messageCount: 2,
    note: 'Site inspection scheduled for upcoming Sunday'
  }
];

export const initialReferrals: ReferralItem[] = [
  {
    id: 'ref1',
    sl: '01',
    name: 'Md. Jahid Parvez',
    phone: '01640510100',
    email: 'jahid.parvez@gmail.com',
    occupation: 'Private Service',
    nid: '256983698',
    dob: '09-01-1996',
    instituteCompany: 'Dhaka University',
    address: '28 Kallayanpur, Beside Bus Stop, Mirpur, Dhaka',
    bloodGroup: 'B+',
    bkashNumber: '01640510100',
    branch: 'Dhaka Head Office',
    referralType: 'Agent',
    totalVisitors: 200,
    enrolledBookings: 20,
    interested: 50,
    date: '25-06-2025',
    commission: 50000,
    status: 'Active',
    paymentHistory: {
      totalCommission: 50000,
      withdrawn: 20000,
      currentBalance: 30000,
    }
  },
  {
    id: 'ref2',
    sl: '02',
    name: 'Md. Karim Mia',
    phone: '01711223344',
    email: 'karim.mia@referral.com',
    occupation: 'Architect',
    nid: '198273645',
    dob: '12-05-1990',
    instituteCompany: 'BUET',
    address: 'Dhanmondi Road 11, Dhaka',
    bloodGroup: 'A+',
    bkashNumber: '01711223344',
    branch: 'Gulshan Branch',
    referralType: 'Student/Influencer/Agent',
    totalVisitors: 56,
    enrolledBookings: 47,
    interested: 89,
    date: '25-06-2025',
    commission: 4700,
    status: 'Active'
  },
  {
    id: 'ref3',
    sl: '03',
    name: 'Farhan Islam',
    phone: '01833445566',
    email: 'farhan@realagent.bd',
    occupation: 'Real Estate Broker',
    nid: '887766554',
    dob: '03-11-1988',
    instituteCompany: 'Property Associates',
    address: 'Agrabad C/A, Chattogram',
    bloodGroup: 'O+',
    bkashNumber: '01833445566',
    branch: 'Chattogram Branch',
    referralType: 'Agent',
    totalVisitors: 120,
    enrolledBookings: 15,
    interested: 35,
    date: '10-04-2025',
    commission: 15000,
    status: 'Active'
  }
];

export const initialCallLogs: CallLog[] = [
  {
    id: 'cl1',
    leadId: '202625067',
    leadName: 'Md. Karim Shah',
    projectName: 'Purbachal Green City Project',
    phone: '01640510100',
    email: 'karim56@gmail.com',
    type: 'Enrolled',
    date: 'March 05, 2026',
    time: '2:30 PM',
    notes: 'Great Conversation. Md. Karim Shah has enrolled in our premium plot booking package. He is very interested about the project amenities and location benefits. Scheduled onboarding call for next week.'
  },
  {
    id: 'cl2',
    leadId: '202625067',
    leadName: 'Md. Karim Shah',
    projectName: 'Purbachal Green City Project',
    phone: '01640510100',
    email: 'karim56@gmail.com',
    type: 'Call',
    date: 'March 05, 2026',
    time: '2:30 PM',
    notes: 'Great Conversation. Discussed 5 Katha South Facing plot layout and installment payment options.'
  },
  {
    id: 'cl3',
    leadId: '202625067',
    leadName: 'Md. Karim Shah',
    projectName: 'Purbachal Green City Project',
    phone: '01640510100',
    email: 'karim56@gmail.com',
    type: 'Interested',
    date: 'March 05, 2026',
    time: '2:30 PM',
    notes: 'Interested in site visit on Friday morning with family members.'
  },
  {
    id: 'cl4',
    leadId: '202625067',
    leadName: 'Md. Karim Shah',
    projectName: 'Purbachal Green City Project',
    phone: '01640510100',
    email: 'karim56@gmail.com',
    type: 'Busy',
    date: 'March 05, 2026',
    time: '2:30 PM',
    notes: 'Client in a meeting. Call rescheduled for evening 6 PM.'
  },
  {
    id: 'cl5',
    leadId: '202625067',
    leadName: 'Md. Karim Shah',
    projectName: 'Purbachal Green City Project',
    phone: '01640510100',
    email: 'karim56@gmail.com',
    type: 'Call',
    date: 'March 05, 2026',
    time: '2:30 PM',
    notes: 'Followed up on land registration process and Rajuk approval documents.'
  }
];

export const mockCategories: LeadCategoryItem[] = [
  {
    id: 'cat1',
    sl: '01',
    name: 'Facebook Leads',
    image: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?auto=format&fit=crop&q=80&w=100',
    totalLeads: 12500,
    status: true,
    note: 'Digital ad campaigns for Promise Assets plot offerings'
  },
  {
    id: 'cat2',
    sl: '02',
    name: 'Google Leads',
    image: 'https://images.unsplash.com/photo-1573804633927-bfcbcd909acd?auto=format&fit=crop&q=80&w=100',
    totalLeads: 12500,
    status: true,
    note: 'Search engine leads searching for land plots in Dhaka'
  },
  {
    id: 'cat3',
    sl: '03',
    name: 'Email Campaign',
    image: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&q=80&w=100',
    totalLeads: 12500,
    status: true,
    note: 'Weekly newsletter subscribers and past real estate inquiries'
  },
  {
    id: 'cat4',
    sl: '04',
    name: 'Facebook Leads',
    image: 'https://images.unsplash.com/photo-1614680376593-902f749f70ba?auto=format&fit=crop&q=80&w=100',
    totalLeads: 12500,
    status: true,
    note: 'Targeted luxury villa campaign leads'
  }
];

export const initialNotifications: NotificationItem[] = [
  {
    id: 'n1',
    title: 'Lead Follow-up Reminder',
    message: 'Follow up with Md. Rahim Mia regarding his Purbachal 5 Katha plot inquiry',
    timeAgo: '15 minutes ago',
    isRead: false,
    type: 'lead-reminder'
  },
  {
    id: 'n2',
    title: 'Site Visit Confirmation',
    message: 'Confirm Saturday site visit with Raja Jisan Khan for Bashundhara Block-I',
    timeAgo: '30 minutes ago',
    isRead: false,
    type: 'lead-reminder'
  },
  {
    id: 'n3',
    title: 'Commercial Quote Requested',
    message: 'Send updated floorplan & pricing to Karim Khandokar for Gulshan Plaza',
    timeAgo: '45 minutes ago',
    isRead: false,
    type: 'lead-reminder'
  },
  {
    id: 'n4',
    title: 'New Support Tickets',
    message: '15 Items Pending Plot Allotment Verification',
    timeAgo: '1 hour ago',
    isRead: true,
    type: 'support'
  },
  {
    id: 'n5',
    title: 'Pending Plot Bookings',
    message: '08 Items Pending Manager Signature & Allotment Deed',
    timeAgo: '2 hours ago',
    isRead: false,
    type: 'approval'
  }
];

export const mockReportRows: ReportRow[] = [
  {
    id: 'r1',
    consultant: 'Rahima Akter',
    projectName: 'Purbachal Green City Phase-1',
    branch: 'Mirpur Branch',
    totalLeads: 60,
    assignedLeads: 60,
    contacted: 45,
    remaining: 15,
    busy: 5,
    interested: 18,
    followUp: 12,
    enrolled: 18,
    cancelled: 4,
    notReceived: 3,
    callRejected: 3,
    progress: '18/60'
  },
  {
    id: 'r2',
    consultant: 'Md. Rahim Sarder',
    projectName: 'Bashundhara Luxury Heights',
    branch: 'Gazipur Regional',
    totalLeads: 55,
    assignedLeads: 55,
    contacted: 40,
    remaining: 15,
    busy: 6,
    interested: 16,
    followUp: 10,
    enrolled: 15,
    cancelled: 5,
    notReceived: 4,
    callRejected: 2,
    progress: '15/55'
  },
  {
    id: 'r3',
    consultant: 'Siddique Rahman',
    projectName: 'Chattogram Commercial Avenue',
    branch: 'Chattogram Branch',
    totalLeads: 70,
    assignedLeads: 70,
    contacted: 52,
    remaining: 18,
    busy: 8,
    interested: 20,
    followUp: 14,
    enrolled: 22,
    cancelled: 3,
    notReceived: 3,
    callRejected: 2,
    progress: '22/70'
  },
  {
    id: 'r4',
    consultant: 'Nazma Begum',
    projectName: 'Uttara Sector 11 Residency',
    branch: 'Uttara Branch',
    totalLeads: 45,
    assignedLeads: 45,
    contacted: 35,
    remaining: 10,
    busy: 4,
    interested: 12,
    followUp: 9,
    enrolled: 14,
    cancelled: 2,
    notReceived: 2,
    callRejected: 2,
    progress: '14/45'
  },
  {
    id: 'r5',
    consultant: 'Md. Karim Shah',
    projectName: 'Gulshan Avenue Plaza',
    branch: 'Dhaka Head Office',
    totalLeads: 80,
    assignedLeads: 80,
    contacted: 62,
    remaining: 18,
    busy: 9,
    interested: 25,
    followUp: 18,
    enrolled: 28,
    cancelled: 4,
    notReceived: 3,
    callRejected: 3,
    progress: '28/80'
  },
  {
    id: 'r6',
    consultant: 'Rahima Akter',
    projectName: 'Dhanmondi Lake View Luxury Condo',
    branch: 'Dhaka Head Office',
    totalLeads: 65,
    assignedLeads: 65,
    contacted: 48,
    remaining: 17,
    busy: 7,
    interested: 19,
    followUp: 13,
    enrolled: 20,
    cancelled: 3,
    notReceived: 2,
    callRejected: 1,
    progress: '20/65'
  },
  {
    id: 'r7',
    consultant: 'Siddique Rahman',
    projectName: 'Purbachal Sector 4 Villa Enclave',
    branch: 'Mirpur Branch',
    totalLeads: 50,
    assignedLeads: 50,
    contacted: 38,
    remaining: 12,
    busy: 5,
    interested: 14,
    followUp: 11,
    enrolled: 16,
    cancelled: 2,
    notReceived: 2,
    callRejected: 1,
    progress: '16/50'
  },
  {
    id: 'r8',
    consultant: 'Md. Rahim Sarder',
    projectName: 'Banani Commercial Tower',
    branch: 'Dhaka Head Office',
    totalLeads: 90,
    assignedLeads: 90,
    contacted: 72,
    remaining: 18,
    busy: 10,
    interested: 28,
    followUp: 20,
    enrolled: 32,
    cancelled: 5,
    notReceived: 3,
    callRejected: 2,
    progress: '32/90'
  },
  {
    id: 'r9',
    consultant: 'Nazma Begum',
    projectName: 'Gazipur Industrial & Housing Park',
    branch: 'Gazipur Regional',
    totalLeads: 40,
    assignedLeads: 40,
    contacted: 28,
    remaining: 12,
    busy: 4,
    interested: 11,
    followUp: 8,
    enrolled: 11,
    cancelled: 3,
    notReceived: 2,
    callRejected: 1,
    progress: '11/40'
  },
  {
    id: 'r10',
    consultant: 'Md. Karim Shah',
    projectName: 'Jolshiri Abashon Block-B',
    branch: 'Uttara Branch',
    totalLeads: 52,
    assignedLeads: 52,
    contacted: 40,
    remaining: 12,
    busy: 5,
    interested: 15,
    followUp: 11,
    enrolled: 17,
    cancelled: 2,
    notReceived: 2,
    callRejected: 1,
    progress: '17/52'
  },
  {
    id: 'r11',
    consultant: 'Rahima Akter',
    projectName: 'Kanchpur Smart City Project',
    branch: 'Mirpur Branch',
    totalLeads: 38,
    assignedLeads: 38,
    contacted: 26,
    remaining: 12,
    busy: 4,
    interested: 10,
    followUp: 8,
    enrolled: 9,
    cancelled: 2,
    notReceived: 3,
    callRejected: 2,
    progress: '9/38'
  },
  {
    id: 'r12',
    consultant: 'Siddique Rahman',
    projectName: 'Savar Epitome Villa Enclave',
    branch: 'Mirpur Branch',
    totalLeads: 42,
    assignedLeads: 42,
    contacted: 30,
    remaining: 12,
    busy: 4,
    interested: 12,
    followUp: 8,
    enrolled: 12,
    cancelled: 2,
    notReceived: 2,
    callRejected: 2,
    progress: '12/42'
  },
  {
    id: 'r13',
    consultant: 'Md. Rahim Sarder',
    projectName: 'Agrabad Commercial Hub',
    branch: 'Chattogram Branch',
    totalLeads: 68,
    assignedLeads: 68,
    contacted: 52,
    remaining: 16,
    busy: 7,
    interested: 20,
    followUp: 15,
    enrolled: 24,
    cancelled: 3,
    notReceived: 2,
    callRejected: 1,
    progress: '24/68'
  },
  {
    id: 'r14',
    consultant: 'Nazma Begum',
    projectName: 'Cox\'s Bazar Beachfront Apartments',
    branch: 'Dhaka Head Office',
    totalLeads: 75,
    assignedLeads: 75,
    contacted: 58,
    remaining: 17,
    busy: 8,
    interested: 22,
    followUp: 16,
    enrolled: 25,
    cancelled: 4,
    notReceived: 3,
    callRejected: 2,
    progress: '25/75'
  },
  {
    id: 'r15',
    consultant: 'Md. Karim Shah',
    projectName: 'Sylhet Airport Road Villas',
    branch: 'Uttara Branch',
    totalLeads: 35,
    assignedLeads: 35,
    contacted: 25,
    remaining: 10,
    busy: 3,
    interested: 9,
    followUp: 7,
    enrolled: 10,
    cancelled: 2,
    notReceived: 2,
    callRejected: 2,
    progress: '10/35'
  },
  {
    id: 'r16',
    consultant: 'Rahima Akter',
    projectName: 'Rajshahi Padma View Enclave',
    branch: 'Mirpur Branch',
    totalLeads: 30,
    assignedLeads: 30,
    contacted: 20,
    remaining: 10,
    busy: 3,
    interested: 8,
    followUp: 6,
    enrolled: 8,
    cancelled: 2,
    notReceived: 2,
    callRejected: 1,
    progress: '8/30'
  },
  {
    id: 'r17',
    consultant: 'Siddique Rahman',
    projectName: 'Khulna City Plaza Commercial',
    branch: 'Gazipur Regional',
    totalLeads: 28,
    assignedLeads: 28,
    contacted: 18,
    remaining: 10,
    busy: 2,
    interested: 7,
    followUp: 5,
    enrolled: 7,
    cancelled: 1,
    notReceived: 2,
    callRejected: 1,
    progress: '7/28'
  },
  {
    id: 'r18',
    consultant: 'Md. Rahim Sarder',
    projectName: 'Barishal Riverview Smart Housing',
    branch: 'Dhaka Head Office',
    totalLeads: 32,
    assignedLeads: 32,
    contacted: 22,
    remaining: 10,
    busy: 3,
    interested: 8,
    followUp: 6,
    enrolled: 9,
    cancelled: 2,
    notReceived: 1,
    callRejected: 1,
    progress: '9/32'
  }
];
