import { Lead, Salesman, ReferralItem, CallLog, LeadCategoryItem, NotificationItem, ReportRow, LeadSourceItem } from './types';

export const mockSalesmen: Salesman[] = [
  {
    id: 's1',
    name: 'Md. Rahim Sarder',
    title: 'Sr. Real Estate Executive',
    department: 'Luxury Residential & Commercial',
    avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&q=80&w=200',
    phone: '01640510100',
    email: 'rahim.sarder@promiseassets.com',
    totalLeadAssign: 60,
    bookedSold: 30,
    contacted: 30,
    lost: 30,
    performanceRate: 50,
    score: '92/100',
    isTopPerformer: true,
  },
  {
    id: 's2',
    name: 'Siddique Rahman',
    title: 'Senior Property Advisor',
    department: 'Bashundhara & Purbachal Plots',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=200',
    phone: '01712345678',
    email: 'siddique.r@promiseassets.com',
    totalLeadAssign: 75,
    bookedSold: 42,
    contacted: 25,
    lost: 8,
    performanceRate: 90,
    score: '95/100',
    isTopPerformer: true,
  },
  {
    id: 's3',
    name: 'Md. Karim Shah',
    title: 'Senior Real Estate Consultant',
    department: 'Gulshan & Banani Luxury Enclave',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=200',
    phone: '01640510101',
    email: 'karim56@gmail.com',
    totalLeadAssign: 50,
    bookedSold: 20,
    contacted: 20,
    lost: 10,
    performanceRate: 78,
    score: '88/100',
  },
  {
    id: 's4',
    name: 'Nazma Begum',
    title: 'Commercial Property Lead',
    department: 'Uttara Commercial Towers',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=200',
    phone: '01898765432',
    email: 'nazma.begum@promiseassets.com',
    totalLeadAssign: 60,
    bookedSold: 30,
    contacted: 30,
    lost: 30,
    performanceRate: 50,
    score: '82/100',
  }
];

export const initialLeads: Lead[] = [
  {
    id: 'L01',
    sl: '01',
    date: '01.01.2026',
    name: 'Md. Rahim Mia',
    phone: '01700066699',
    email: 'jccdhaka@gmail.com',
    occupation: 'Businessman',
    nid: '256983698',
    address: 'Kallayanpur, Dhaka',
    projectName: 'Purbachal Green Valley Project',
    requiredPlotSize: '5 Katha',
    facingPreference: 'South',
    budgetLimit: '৳ 1.5 Crore',
    projectType: 'Plot',
    prefTime: 'Morning',
    status: 'Booking Confirmed',
    assignedSalesman: 'Siddique Rahman',
    source: 'Referral',
    referralId: 'ref1',
    referralName: 'Md. Jahid Parvez',
    referralPhone: '01640510100',
    referralType: 'Agent',
    lastCallDate: '2026-02-20',
    callCount: 3,
    messageCount: 3,
    note: 'Interest to book 5 Katha South Facing plot by 14-03-2026',
  },
  {
    id: 'L02',
    sl: '02',
    date: '02.01.2026',
    name: 'Raja Jisan Khan',
    phone: '01700066699',
    email: 'jccdhaka@gmail.com',
    occupation: 'Corporate GM',
    nid: '198273645',
    address: 'Kallayanpur, Dhaka',
    projectName: 'Bashundhara Block-I Luxury Heights',
    requiredPlotSize: '2400 sqft',
    facingPreference: 'North',
    budgetLimit: '৳ 2.2 Crore',
    projectType: 'Residential',
    prefTime: 'Night',
    status: 'Closed Lost',
    assignedSalesman: 'Siddique Rahman',
    source: 'Facebook',
    lastCallDate: '2026-02-20',
    callCount: 3,
    messageCount: 3,
    note: 'Budget Problem',
    lostReason: 'Budget'
  },
  {
    id: 'L03',
    sl: '03',
    date: '03.01.2026',
    name: 'Karim Khandokar',
    phone: '01700066699',
    email: 'jccdhaka@gmail.com',
    occupation: 'Doctor',
    nid: '887766554',
    address: 'Kallayanpur, Dhaka',
    projectName: 'Gulshan Avenue Commercial Plaza',
    requiredPlotSize: '1800 sqft',
    facingPreference: 'Corner',
    budgetLimit: '৳ 3.5 Crore',
    projectType: 'Commercial',
    prefTime: 'Evening',
    status: 'Contacted',
    assignedSalesman: 'Md. Rahim Sarder',
    source: 'WhatsApp',
    lastCallDate: '2026-02-20',
    callCount: 4,
    messageCount: 2,
    note: 'Scheduled site visit for upcoming Saturday'
  },
  {
    id: 'L04',
    sl: '04',
    date: '04.01.2026',
    name: 'Abdul Karim',
    phone: '01700066699',
    email: 'jccdhaka@gmail.com',
    occupation: 'Expatriate (Dubai)',
    nid: '445566778',
    address: 'Banani, Dhaka',
    projectName: 'Purbachal Sector 4 Villa Project',
    requiredPlotSize: '10 Katha',
    facingPreference: 'South',
    budgetLimit: '৳ 4.0 Crore',
    projectType: 'Luxury Villa',
    prefTime: 'Afternoon',
    status: 'Follow-up Scheduled',
    assignedSalesman: 'Siddique Rahman',
    source: 'Youtube',
    lastCallDate: '2026-02-20',
    callCount: 3,
    messageCount: 3,
    note: 'Waiting for bank loan approval from HSBC'
  },
  {
    id: 'L05',
    sl: '05',
    date: '05.01.2026',
    name: 'Rajib Hossain',
    phone: '01700066699',
    email: 'jccdhaka@gmail.com',
    occupation: 'Software Architect',
    nid: '998877665',
    address: 'Dhanmondi, Dhaka',
    projectName: 'Dhanmondi Lake View Luxury Condo',
    requiredPlotSize: '2100 sqft',
    facingPreference: 'East',
    budgetLimit: '৳ 1.8 Crore',
    projectType: 'Residential',
    prefTime: 'Morning',
    status: 'Brochure & Price Shared',
    assignedSalesman: 'Md. Karim Shah',
    source: 'Facebook',
    lastCallDate: '2026-02-20',
    callCount: 2,
    messageCount: 5,
    note: 'Requested updated floor plan and payment schedule'
  },
  {
    id: 'L06',
    sl: '06',
    date: '06.01.2026',
    name: 'Tabassum Tuha',
    phone: '01700066699',
    email: 'jccdhaka@gmail.com',
    occupation: 'Professor',
    nid: '332211445',
    address: 'Uttara, Dhaka',
    projectName: 'Uttara Model Town Sector 11 Plot',
    requiredPlotSize: '3 Katha',
    facingPreference: 'South',
    budgetLimit: '৳ 1.2 Crore',
    projectType: 'Plot',
    prefTime: 'Afternoon',
    status: 'Site Visit Completed',
    assignedSalesman: 'Siddique Rahman',
    source: 'Referral',
    referralId: 'ref2',
    referralName: 'Md. Karim Mia',
    referralPhone: '01711223344',
    referralType: 'Student/Influencer/Agent',
    lastCallDate: '2026-02-20',
    callCount: 5,
    messageCount: 4,
    note: 'Site visit completed. Interested in booking token.'
  }
];

export const initialReferrals: ReferralItem[] = [
  {
    id: 'ref1',
    sl: '01',
    name: 'Md. Jahid Parvez',
    phone: '01640510100',
    email: 'jahid.parvez@gmail.com',
    occupation: 'Private Service',
    nid: '256983698',
    dob: '09-01-1996',
    instituteCompany: 'Dhaka University',
    address: '28 Kallayanpur, Beside Bus Stop, Mirpur, Dhaka',
    bloodGroup: 'B+',
    bkashNumber: '01640510100',
    branch: 'Dhaka Head Office',
    referralType: 'Agent',
    totalVisitors: 200,
    enrolledBookings: 20,
    interested: 50,
    date: '25-06-2025',
    commission: 50000,
    status: 'Active',
    paymentHistory: {
      totalCommission: 50000,
      withdrawn: 20000,
      currentBalance: 30000,
    }
  },
  {
    id: 'ref2',
    sl: '02',
    name: 'Md. Karim Mia',
    phone: '01711223344',
    email: 'karim.mia@referral.com',
    occupation: 'Architect',
    nid: '198273645',
    dob: '12-05-1990',
    instituteCompany: 'BUET',
    address: 'Dhanmondi Road 11, Dhaka',
    bloodGroup: 'A+',
    bkashNumber: '01711223344',
    branch: 'Gulshan Branch',
    referralType: 'Student/Influencer/Agent',
    totalVisitors: 56,
    enrolledBookings: 47,
    interested: 89,
    date: '25-06-2025',
    commission: 4700,
    status: 'Active'
  },
  {
    id: 'ref3',
    sl: '03',
    name: 'Farhan Islam',
    phone: '01833445566',
    email: 'farhan@realagent.bd',
    occupation: 'Real Estate Broker',
    nid: '887766554',
    dob: '03-11-1988',
    instituteCompany: 'Property Associates',
    address: 'Agrabad C/A, Chattogram',
    bloodGroup: 'O+',
    bkashNumber: '01833445566',
    branch: 'Chattogram Branch',
    referralType: 'Agent',
    totalVisitors: 120,
    enrolledBookings: 15,
    interested: 35,
    date: '10-04-2025',
    commission: 15000,
    status: 'Active'
  }
];

export const initialCallLogs: CallLog[] = [
  {
    id: 'cl1',
    leadId: '202625067',
    leadName: 'Jitu Guha',
    projectName: 'Purbachal Green City',
    phone: '+8801317371778',
    email: 'jitu.guha@gmail.com',
    type: 'Booking Confirmed',
    channel: 'Office Meeting',
    date: 'August 05, 2026',
    time: '04:15 PM',
    duration: '00:45:00',
    executiveName: 'Siddique Rahman',
    callResult: 'Booking Confirmed',
    nextFollowUpDate: 'August 12, 2026',
    notes: 'Token Money Received: ৳ 1,00,000 via Pay Order #PO-98241 for 5 Katha Plot #104, Block-B. Booking receipt issued and handed over.'
  },
  {
    id: 'cl2',
    leadId: '202625067',
    leadName: 'Jitu Guha',
    projectName: 'Purbachal Green City',
    phone: '+8801317371778',
    email: 'jitu.guha@gmail.com',
    type: 'Negotiation',
    channel: 'Office Meeting',
    date: 'August 03, 2026',
    time: '11:30 AM',
    duration: '00:30:15',
    executiveName: 'Siddique Rahman',
    callResult: 'Negotiation',
    nextFollowUpDate: 'August 05, 2026',
    notes: 'Head Office Negotiation Meeting: Discussed 36-month flexible installment scheme and 5% spot discount on 30% down payment. Client expressed high satisfaction.'
  },
  {
    id: 'cl3',
    leadId: '202625067',
    leadName: 'Jitu Guha',
    projectName: 'Purbachal Green City',
    phone: '+8801317371778',
    email: 'jitu.guha@gmail.com',
    type: 'Site Visit Completed',
    channel: 'Site Visit',
    date: 'August 01, 2026',
    time: '10:00 AM',
    duration: '02:15:00',
    executiveName: 'Siddique Rahman',
    callResult: 'Site Visit Completed',
    nextFollowUpDate: 'August 03, 2026',
    notes: 'Physical Site Visit Completed: Accompanied Mr. Guha & family in company AC microbus to Sector-3. Inspected Plot #104 (South Facing, 40ft road). Client loved the lake-facing view.'
  },
  {
    id: 'cl4',
    leadId: '202625067',
    leadName: 'Jitu Guha',
    projectName: 'Purbachal Green City',
    phone: '+8801317371778',
    email: 'jitu.guha@gmail.com',
    type: 'Brochure & Price Shared',
    channel: 'WhatsApp',
    date: 'July 28, 2026',
    time: '02:20 PM',
    duration: '00:05:00',
    executiveName: 'Siddique Rahman',
    callResult: 'Brochure & Price Shared',
    nextFollowUpDate: 'August 01, 2026',
    notes: 'Dispatched 2026 Master Plan PDF, 3D Layout Map, and Sector-3 Price List via WhatsApp. Client confirmed receipt and requested weekend site visit.'
  },
  {
    id: 'cl5',
    leadId: '202625067',
    leadName: 'Jitu Guha',
    projectName: 'Purbachal Green City',
    phone: '+8801317371778',
    email: 'jitu.guha@gmail.com',
    type: 'First Contact',
    channel: 'Phone Call',
    date: 'July 26, 2026',
    time: '05:40 PM',
    duration: '00:06:42',
    executiveName: 'Siddique Rahman',
    callResult: 'Contacted',
    nextFollowUpDate: 'July 28, 2026',
    notes: 'Outbound Discovery Call: Customer inquired about residential plot sizes, Rajuk approval status, and distance from Kuril Flyover. High purchase intent confirmed.'
  },
  {
    id: 'cl6',
    leadId: '202625067',
    leadName: 'Jitu Guha',
    projectName: 'Purbachal Green City',
    phone: '+8801317371778',
    email: 'jitu.guha@gmail.com',
    type: 'Assigned',
    channel: 'System',
    date: 'July 25, 2026',
    time: '09:15 AM',
    duration: '00:00:00',
    executiveName: 'System Admin',
    callResult: 'Assigned',
    nextFollowUpDate: 'July 26, 2026',
    notes: 'New Facebook Lead Captured and automatically assigned to Sales Executive Siddique Rahman.'
  },
  {
    id: 'cl7',
    leadId: 'lead_1',
    leadName: 'Md. Karim Shah',
    projectName: 'Purbachal Green City Project',
    phone: '01640510100',
    email: 'karim56@gmail.com',
    type: 'Booking Confirmed',
    channel: 'Office Meeting',
    date: 'August 04, 2026',
    time: '02:30 PM',
    duration: '00:35:00',
    executiveName: 'Siddique Rahman',
    callResult: 'Booking Confirmed',
    nextFollowUpDate: 'August 10, 2026',
    notes: 'Client booked 5 Katha South Facing plot. Handed over booking acknowledgment and agreement schedule.'
  },
  {
    id: 'cl8',
    leadId: 'lead_1',
    leadName: 'Md. Karim Shah',
    projectName: 'Purbachal Green City Project',
    phone: '01640510100',
    email: 'karim56@gmail.com',
    type: 'Brochure & Price Shared',
    channel: 'WhatsApp',
    date: 'August 02, 2026',
    time: '11:15 AM',
    duration: '00:03:00',
    executiveName: 'Siddique Rahman',
    callResult: 'Brochure & Price Shared',
    nextFollowUpDate: 'August 04, 2026',
    notes: 'Shared Rajuk approval papers, layout map, and installment options over WhatsApp.'
  }
];

export const mockCategories: LeadCategoryItem[] = [
  {
    id: 'cat1',
    sl: '01',
    name: 'Facebook Leads',
    image: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?auto=format&fit=crop&q=80&w=100',
    totalLeads: 12500,
    status: true,
    note: 'Digital ad campaigns for Promise Assets plot offerings'
  },
  {
    id: 'cat2',
    sl: '02',
    name: 'Google Leads',
    image: 'https://images.unsplash.com/photo-1573804633927-bfcbcd909acd?auto=format&fit=crop&q=80&w=100',
    totalLeads: 12500,
    status: true,
    note: 'Search engine leads searching for land plots in Dhaka'
  },
  {
    id: 'cat3',
    sl: '03',
    name: 'Email Campaign',
    image: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&q=80&w=100',
    totalLeads: 12500,
    status: true,
    note: 'Weekly newsletter subscribers and past real estate inquiries'
  },
  {
    id: 'cat4',
    sl: '04',
    name: 'Facebook Leads',
    image: 'https://images.unsplash.com/photo-1614680376593-902f749f70ba?auto=format&fit=crop&q=80&w=100',
    totalLeads: 12500,
    status: true,
    note: 'Targeted luxury villa campaign leads'
  }
];

export const initialNotifications: NotificationItem[] = [
  {
    id: 'n1',
    title: 'Lead Follow-up Reminder',
    message: 'Follow up with Md. Rahim Mia regarding his Purbachal 5 Katha plot inquiry',
    timeAgo: '15 minutes ago',
    isRead: false,
    type: 'lead-reminder'
  },
  {
    id: 'n2',
    title: 'Site Visit Confirmation',
    message: 'Confirm Saturday site visit with Raja Jisan Khan for Bashundhara Block-I',
    timeAgo: '30 minutes ago',
    isRead: false,
    type: 'lead-reminder'
  },
  {
    id: 'n3',
    title: 'Commercial Quote Requested',
    message: 'Send updated floorplan & pricing to Karim Khandokar for Gulshan Plaza',
    timeAgo: '45 minutes ago',
    isRead: false,
    type: 'lead-reminder'
  },
  {
    id: 'n4',
    title: 'New Support Tickets',
    message: '15 Items Pending Plot Allotment Verification',
    timeAgo: '1 hour ago',
    isRead: true,
    type: 'support'
  },
  {
    id: 'n5',
    title: 'Pending Plot Bookings',
    message: '08 Items Pending Manager Signature & Allotment Deed',
    timeAgo: '2 hours ago',
    isRead: false,
    type: 'approval'
  }
];

export const mockReportRows: ReportRow[] = [
  {
    id: 'r1',
    consultant: 'Rahima Akter',
    projectName: 'Purbachal Green City / Mirpur Branch',
    branch: 'Mirpur',
    totalLeads: 60,
    assignedLeads: 60,
    contacted: 30,
    remaining: 30,
    busy: 15,
    interested: 10,
    followUp: 10,
    enrolled: 10,
    cancelled: 10,
    notReceived: 10,
    callRejected: 5,
    progress: '30/50'
  },
  {
    id: 'r2',
    consultant: 'Rahima Akter',
    projectName: 'Bashundhara Luxury Heights / Gazipur',
    branch: 'Gazipur',
    totalLeads: 60,
    assignedLeads: 60,
    contacted: 30,
    remaining: 30,
    busy: 15,
    interested: 10,
    followUp: 10,
    enrolled: 10,
    cancelled: 10,
    notReceived: 10,
    callRejected: 5,
    progress: '30/50'
  },
  {
    id: 'r3',
    consultant: 'Rahima Akter',
    projectName: 'Chattogram Commercial Avenue',
    branch: 'Chattogram',
    totalLeads: 60,
    assignedLeads: 60,
    contacted: 30,
    remaining: 30,
    busy: 15,
    interested: 10,
    followUp: 10,
    enrolled: 10,
    cancelled: 10,
    notReceived: 10,
    callRejected: 5,
    progress: '30/50'
  }
];

export const mockLeadSources: LeadSourceItem[] = [
  { id: 'src-1', sl: 1, name: 'Facebook', leadsCount: 429, currentWeek: 0, lastWeek: 2, performancePercent: -100.0, status: 'Active' },
  { id: 'src-2', sl: 2, name: 'Friend of Friend', leadsCount: 37, currentWeek: 2, lastWeek: 8, performancePercent: -75.0, status: 'Active' },
  { id: 'src-3', sl: 3, name: 'Google', leadsCount: 0, currentWeek: 0, lastWeek: 0, performancePercent: 0, status: 'Active' },
  { id: 'src-4', sl: 4, name: 'Messenger', leadsCount: 1, currentWeek: 0, lastWeek: 0, performancePercent: 0, status: 'Active' },
  { id: 'src-5', sl: 5, name: 'Phone', leadsCount: 28, currentWeek: 1, lastWeek: 4, performancePercent: -75.0, status: 'Active' },
  { id: 'src-6', sl: 6, name: 'Referrer', leadsCount: 37, currentWeek: 5, lastWeek: 4, performancePercent: 25.0, status: 'Active' },
  { id: 'src-7', sl: 7, name: 'Walking Visitor', leadsCount: 74, currentWeek: 3, lastWeek: 6, performancePercent: -50.0, status: 'Active' },
  { id: 'src-8', sl: 8, name: 'Website', leadsCount: 1, currentWeek: 0, lastWeek: 0, performancePercent: 0, status: 'Active' },
  { id: 'src-9', sl: 9, name: 'WhatsApp', leadsCount: 40, currentWeek: 10, lastWeek: 4, performancePercent: 150.0, status: 'Active' },
];
